services:
  postgres:
    image: postgres:15
    container_name: unictive-spring-postgres
    environment:
      POSTGRES_USER: unictive
      POSTGRES_PASSWORD: unictive
      POSTGRES_DB: unictive-db
    ports:
      - "5441:5432"
    volumes:
      - java_postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: boilerplate-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  java_postgres_data:
  minio_data: