name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy Spring Boot to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: biar gak overlap

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Java (misal pakai JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3️⃣ Build project (clean + install)
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # 4️⃣ Setup Fly.io CLI
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      # 5️⃣ Deploy ke Fly.io
      - name: Deploy to Fly.io
        run: flyctl deploy --app=${{ secrets.FLY_APP_NAME }} --build-only --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
